[package]
name = "linonono_debug_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.95"
colog = "1.3.0"
linono_extractor = { "path" = "../linono_extractor"}
