name: Deploy github page

on:
  workflow_run:
    workflows: [Docker Image CI]
    types: [completed]
  schedule:
    - cron: "0 4 * * *" 
  
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    container:
      image: baduit/linono:latest
    steps:
      - name: Generate html
        run: |
          pwd
          cd /linono
          mkdir build
          rye run linono html build/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
