[package]
name = "linono_extractor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.95"
chrono = "0.4.39"
colog = "1.3.0"
log = "0.4.25"
scraper = "0.22.0"
ureq = "3.0.5"
